### ISSUE TITLE
link to dropbox article is broken

### ISSUE THREAD

**Issue by brianray** [victor-gil-sepulveda/pyProCT#20]
The docs point to:

  https://dl.dropboxusercontent.com/u/58918851/icv_info.pdf

I am interested in "compactness" and "seperation" measures.

Do you still have this doc? What was it?

**Comment by victor-gil-sepulveda** [comment]
Dear brianray,

I have updated and reuploaded the pdf. This document is indeed the supplementary information (free access) that for the original paper in JCTC.  You can download it from https://dl.dropboxusercontent.com/u/58918851/icv_info.pdf.
The information you need is in chapter 2, and the implementation can be found inside pyproct/clustering/evaluation/metrics

Cheers,
Víctor

**Comment by cerebis** [comment]
Hi Victor, this URL does not seem to be valid as I get a 404 error. Perhaps it has lost its shared permission?

**Comment by victor-gil-sepulveda** [comment]
Hi cerebis,
you are right. There were some wrong links still in the README file, and, in addition, the link poster above was still the old one (my bad). The correct one is:

https://dl.dropboxusercontent.com/u/58918851/pyProCT-SupportingInformation.pdf

Also, I forgot to add the reference to the original article in the README file.  Please consider to cite it in your own works if you think the software or documentation helped you.

Cheers,
Víctor
